### ISSUE TITLE
Mocking framework

### ISSUE THREAD

**Issue by oleksiyp** [K0bin/GesaHu-Android#36]
Hi,

hope find you well with this cold call.

I am an author of [mocking framework for Kotlin](http://mockk.io)

I see you are using mockito-kotlin.

I just want you to be aware that there is solution that fully supports Kotlin and ask to try it in your new/current projects.

I can help you if you answer to this issue.

Thanks and please star [it](https://github.com/oleksiyp/mockk)

**Comment by K0bin** [comment]
I probably won't look into it. I'm not gonna lie, those tests were mostly to just experiment with Unit tests on Android as this app is basically the first Android app I ever wrote and therefore my go to practice new stuff. I never bothered to keep the tests up to date and have for the most part stopped working on the app. It was a hobby project of mine and I was the only one working on it. It ate enough time as it is even without constantly unit testing everything.

MockK looks pretty nice though.
